# Components generated during the build process is called arficats.
# yaml file is in a form of key,value.


artifacts_root: artifacts

# 1.
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1Umai3H4eEdyY5UMeQg3PLp7RkHEbKR1T/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

# 2.
prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5

# 3.
training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5
  
#4.
evaluation:
  trained_model_path: artifacts/training/model.h5
  training_data: artifacts/data_ingestion/Chest-CT-Scan-data
  mlflow_uri: https://dagshub.com/Chanakarn-Luangpirom/MLFlow.mlflow

